### PR TITLE
Adds support for exporting lcov.info files

### PR DESCRIPTION
**Pull request by ssfrr**
These are useful for interoperating with a variety of local visualization
tools, or pulling into e.g. Atom.

### CODE REVIEW

**Comment by ssfrr** [comment]
Oh, I think I also fixed a couple usages of deprecated syntax.

**Comment by kshyatt** [comment]
LGTM. This is awesome.

**Comment by staticfloat** [comment]
:D

**Comment by IainNZ** [comment]
Looks very nice!

**Pull request merged**
