### PR TITLE
Switched from JuliaParser to Base

### PR DESCRIPTION
**Pull request by kshyatt**
This works now with the newest `Base` master.

### CODE REVIEW

**Comment by IainNZ** [comment]
Looks like it might need a `readall` on 0.3, and a test result change on 0.4.

**Comment by kshyatt** [comment]
Got the `0.4` change done. Where is the `readall` needed?

**Comment by IainNZ** [comment]
There error message on 0.3 sez `ERROR: `parse` has no method matching parse(::IOStream)`

**Comment by IainNZ** [comment]
I guess it only takes strings?

**Comment by kshyatt** [comment]
I talked with @IainNZ and we're going to merge then get set for 0.4, which should be coming very soon.

**Pull request merged**
