### PR TITLE
Add clean_file and clean_folder methods to clean up coverage files

### PR DESCRIPTION
**Pull request by ssfrr**
I'm filing this PR on top of the previous lcov PR, so if you're going to merge
both of them do that one first. Let me know if you'd rather I rebase on master.

### CODE REVIEW

**Comment by IainNZ** [comment]
Can you rebase and, while you are at it, turn the comments before the functions into docstrings? Might as well get started on doing that.

**Comment by ssfrr** [comment]
rebased. I went ahead and added docstrings for all exported modules, methods and types in Coverage.jl (unless I missed some).

**Comment by iamed2** [comment]
Would love to see this merged; I was just about to make a PR for the deprecations as they cover most of my screen when testing.

**Comment by IainNZ** [comment]
boom

**Comment by iamed2** [comment]
Thanks!

**Comment by hayd** [comment]
Could you push a release with these changes? Thanks!

**Comment by IainNZ** [comment]
Doing now

**Comment by IainNZ** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/3689

**Comment by hayd** [comment]
Thanks!

**Pull request merged**
