### PR TITLE
Add Codecov.io support

### PR DESCRIPTION
**Pull request by IainNZ**
#57

### CODE REVIEW

**Comment by IainNZ** [comment]
@stevepeak I'm seeing the following response from Codecov:
```
$ julia -e 'cd(Pkg.dir("Coverage")); using Coverage; Codecov.submit(Codecov.process_folder())'
WARNING: This version of the GnuTLS library (2.12.14) is deprecated
and contains known security vulnerabilities. Please upgrade to a
more recent version.
[]
src/codecovio.jl
src/Coverage.jl
src/Coverage.jl.cov
Skipped src/Coverage.jl.cov
ASCIIString "{\"queued\": true, \"uploaded\": true, \"url\": \"http://codecov.io/github/IainNZ/Coverage.jl?ref=b99f0c63f62072355d89e3f3b1360a970785102a\", \"meta\": {\"request\": \"95a74b39-20c0-4b8c-adc0-3e1da65d3e6d\", \"status\": 200}, \"message\": \"Coverage reports upload successfully\"}"
```

Which looks good, but I'm not seeing anything on the Codecov site. Does it only work if its on master?

**Comment by stevepeak** [comment]
*sorry about delay* Are you still experiencing this issue? I can check the logs and uploads to see whats up. But it works on all branches and commit sha. [Here is an upload that took](https://codecov.io/github/IainNZ/Coverage.jl?ref=ird/codecov)

#### Recent changes
- The endpoints no longer require `Content-Type` header to be set. It's simply ignored now and reports are detected automatically.
- Support the many CI companies. [View their environment variables here](https://github.com/codecov/codecov-bash/blob/master/codecov#L121-L229)

**Comment by IainNZ** [comment]
No everything is working, the only glitch is that it shows coverage for the master branch but none has been submitted, so the line numbers don't match.

**Comment by stevepeak** [comment]
Can you send me an example report ex. `src/Coverage.jl.cov` so I can see the format and help you out. The system only keeps raw data uploaded if it failed for 24h soI have no raw reports from this project at the moment. Thanks!

**Comment by IainNZ** [comment]
@stevepeak I'm not submitting raw coverage data, I'm submitting to your JSON endpoint in the format your docs define. I have written code already here, in this package, to convert it the Julia-produced `.cov` files to JSON for use with Coveralls.io, so all this PR does it add a new JSON format and changes the endpoint.

**Comment by stevepeak** [comment]
I see, well when you hack on this again we can sit in a chat room to speed up the integration. I appreciate your support on this, it means a great deal to me :)

**Comment by stevepeak** [comment]
@IainNZ checking in to see if there is any help I can provide with this integration. Thanks!

**Comment by kshyatt** [comment]
I'm here being a pain about this again! Any more progress on this issue?

**Comment by IainNZ** [comment]
Its pretty much done IIRC, and works. Not sure what, if anything, is left to be done except maybe just tidying and more error checking. I don't really have time to get it in though. I can give you commit access to finish off anything that needs to be done if its something you are interested in?

**Comment by kshyatt** [comment]
I don't know a single thing about JSON but I'm down to try to figure this out, if you'd like!

**Comment by IainNZ** [comment]
Looking at it, I think maybe all that really needed to be done was maybe a try catch around the submit. I kind of hate the code layout now, but thats a seperate issue.

**Comment by IainNZ** [comment]
OK you have commit access. Maybe just have a read through of this PR, merge it, and check it works for your needs. Ping me if you get stuck with anything.

**Comment by IainNZ** [comment]
Actually hold on I'll rebase it and force a new build.

**Comment by kshyatt** [comment]
Build appears to have passed, shall we merge?

**Comment by IainNZ** [comment]
Yep

**Comment by kshyatt** [comment]
Awesome! I'll test this out with `CoverageBase` and get back to you. Thanks so much!

**Pull request merged**
