### PR TITLE
Implement `isfuncexpr` locally. Fixes #48.

### LINKED ISSUE #48: [PkgEval] Coverage may have a testing issue on Julia 0.4 (2015-02-09)
[PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) is a script that runs nightly. It attempts to load all Julia packages and run their tests (if available) on both the stable version of Julia (0.3) and the nightly build of the unstable version (0.4). The results of this script are used to generate a [package listing](http://pkg.julialang.org/) enhanced with testing results.

#### On Julia 0.4
* On **2015-02-07** the testing status was `Tests pass.`
* On **2015-02-09** the testing status changed to `Tests fail, but package loads.`

`Tests pass.` means that PackageEvaluator found the tests for your package, executed them, and they all passed.

`Tests fail, but package loads.` means that PackageEvaluator found the tests for your package, executed them, and they didn't pass. However, trying to load your package with `using` worked.

*This issue was filed because your testing status became worse. No additional issues will be filed if your package remains in this state, and no issue will be filed if it improves. If you'd like to opt-out of these status-change messages, reply to this message saying you'd like to and @IainNZ will add an exception. If you'd like to discuss [PackageEvaluator.jl](https://github.com/IainNZ/PackageEvaluator.jl) please file an issue at the repository. For example, your package may be untestable on the test machine due to a dependency - an exception can be added.*

*Test log*:
```
>>> 'Pkg.add("Coverage")' log

WARNING: deprecated syntax "[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/HttpParser/deps/build.jl:42.
Use "Dict(a=>b, ...)" instead.
Submodule 'deps/src/http-parser' (https://github.com/joyent/http-parser.git) registered for path 'deps/src/http-parser'
Cloning into 'deps/src/http-parser'...
Submodule path 'deps/src/http-parser': checked out '80819384450b5511a3d1c424dd92a5843c891364'
make: Entering directory '/home/idunning/pkgtest/.julia/v0.4/HttpParser/deps/src/http-parser'
cc -I. -DHTTP_PARSER_STRICT=0  -Wall -Wextra -Werror -O3  -fPIC -c http_parser.c -o libhttp_parser.o
cc -shared -o libhttp_parser.so libhttp_parser.o
make: Leaving directory '/home/idunning/pkgtest/.julia/v0.4/HttpParser/deps/src/http-parser'

WARNING: deprecated syntax "{a=>b, ...}" at /home/idunning/pkgtest/.julia/v0.4/Nettle/deps/build.jl:25.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/Nettle/deps/build.jl:38.
Use "Dict(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/idunning/pkgtest/.julia/v0.4/GnuTLS/deps/build.jl:15.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/idunning/pkgtest/.julia/v0.4/GnuTLS/deps/build.jl:48.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/idunning/pkgtest/.julia/v0.4/GnuTLS/deps/build.jl:53.
Use "Dict{Any,Any}(a=>b, ...)" instead.

WARNING: deprecated syntax "[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/GnuTLS/deps/build.jl:55.
Use "Dict(a=>b, ...)" instead.
INFO: Installing BinDeps v0.3.7
INFO: Installing Codecs v0.1.3
INFO: Installing Compat v0.2.11
INFO: Installing Coverage v0.0.7
INFO: Installing Dates v0.4.4
INFO: Installing FactCheck v0.2.5
INFO: Installing GnuTLS v0.0.1
INFO: Installing HttpCommon v0.0.11
INFO: Installing HttpParser v0.0.10
INFO: Installing JSON v0.4.0
INFO: Installing JuliaParser v0.6.2
INFO: Installing Nettle v0.1.7
INFO: Installing Requests v0.0.6
INFO: Installing SHA v0.0.3
INFO: Installing URIParser v0.0.3
INFO: Building HttpParser
INFO: Changing Directory to /home/idunning/pkgtest/.julia/v0.4/HttpParser
INFO: Changing Directory to /home/idunning/pkgtest/.julia/v0.4/HttpParser
INFO: Changing Directory to /home/idunning/pkgtest/.julia/v0.4/HttpParser/deps/src
INFO: Attempting to Create directory /home/idunning/pkgtest/.julia/v0.4/HttpParser/deps/usr/lib
INFO: Changing Directory to /home/idunning/pkgtest/.julia/v0.4/HttpParser/deps/src
INFO: Changing Directory to /home/idunning/pkgtest/.julia/v0.4/HttpParser/deps/src
INFO: Building Nettle
INFO: Building GnuTLS
INFO: Package database updated

>>> 'using Coverage' log

WARNING: deprecated syntax "(String=>String)[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/Requests/src/Requests.jl:34.
Use "Dict{String,String}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/idunning/pkgtest/.julia/v0.4/GnuTLS/src/errormap.jl:155.
Use "Dict{Any,Any}(a=>b, ...)" instead.
Julia Version 0.4.0-dev+3225
Commit 6558327 (2015-02-09 04:52 UTC)
Platform Info:
  System: Linux (x86_64-unknown-linux-gnu)
  CPU: Intel(R) Xeon(R) CPU E5-2650 0 @ 2.00GHz
  WORD_SIZE: 64
  BLAS: libopenblas (USE64BITINT DYNAMIC_ARCH NO_AFFINITY Sandybridge)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3
Coverage.MallocInfo[]
WARNING: Set(a,b...) is deprecated, use Set(Any[a,b...]) instead.
 in depwarn at ./deprecated.jl:40
 in call at deprecated.jl:29
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:54
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:54
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:54
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403

>>> test log

WARNING: deprecated syntax "(String=>String)[a=>b, ...]" at /home/idunning/pkgtest/.julia/v0.4/Requests/src/Requests.jl:34.
Use "Dict{String,String}(a=>b, ...)" instead.

WARNING: deprecated syntax "{a=>b, ...}" at /home/idunning/pkgtest/.julia/v0.4/GnuTLS/src/errormap.jl:155.
Use "Dict{Any,Any}(a=>b, ...)" instead.
WARNING: Set(a,b...) is deprecated, use Set(Any[a,b...]) instead.
 in depwarn at ./deprecated.jl:40
 in call at deprecated.jl:29
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:54
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:54
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:54
 in include at ./boot.jl:249
 in include_from_node1 at ./loading.jl:128
 in reload_path at ./loading.jl:152
 in _require at ./loading.jl:67
 in require at ./loading.jl:52
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403
ERROR: LoadError: UndefVarError: isfuncexpr not defined
 in function_body_lines! at /home/idunning/pkgtest/.julia/v0.4/Coverage/src/Coverage.jl:99
 in anonymous at /home/idunning/pkgtest/.julia/v0.4/Coverage/src/Coverage.jl:51
 in open at ./iostream.jl:137
 in amend_coverage_from_src! at /home/idunning/pkgtest/.julia/v0.4/Coverage/src/Coverage.jl:45
 in process_file at /home/idunning/pkgtest/.julia/v0.4/Coverage/src/Coverage.jl:125
 in anonymous at /home/idunning/pkgtest/.julia/v0.4/Coverage/test/runtests.jl:10
 in cd at ./file.jl:20
 in include at ./boot.jl:249
 in include_from_node1 at loading.jl:128
 in process_options at ./client.jl:319
 in _start at ./client.jl:403
while loading /home/idunning/pkgtest/.julia/v0.4/Coverage/test/runtests.jl, in expression starting on line 9
Coverage.MallocInfo[]

INFO: Computing test dependencies for Coverage...
INFO: Installing Docile v0.4.1
INFO: Testing Coverage
==============================[ ERROR: Coverage ]===============================

failed process: Process(`/home/idunning/julia04/usr/bin/julia --check-bounds=yes --code-coverage=none --color=no /home/idunning/pkgtest/.julia/v0.4/Coverage/test/runtests.jl`, ProcessExited(1)) [1]

================================================================================
INFO: Removing Docile v0.4.1
ERROR: Coverage had test errors
 in error at error.jl:19
 in test at pkg/entry.jl:717
 in anonymous at pkg/dir.jl:28
 in cd at file.jl:20
 in cd at pkg/dir.jl:28
 in test at pkg.jl:69
 in process_options at ./client.jl:241
 in _start at ./client.jl:403


>>> end of log
```

### PR DESCRIPTION
**Pull request by timholy**
This is needed now that Base.Cartesian has been greatly slimmed down.

### CODE REVIEW

**Comment by IainNZ** [comment]
Ah I was wondering what this was about

**Comment by timholy** [comment]
OK with you if I merge?

**Comment by IainNZ** [comment]
Oh yes! Was just waiting for Travis when I commented. Feel free to merge any PRs on Coverage.jl

**Comment by IainNZ** [comment]
Can you tag a new release?

**Comment by timholy** [comment]
Sure.

**Comment by timholy** [comment]
Done.

**Pull request merged**
