### PR TITLE
Big Refactor

### PR DESCRIPTION
**Pull request by IainNZ**

### CODE REVIEW

**Comment by IainNZ** [comment]
OK @staticfloat @kshyatt its done. This is a breaking change if you were using the internals, as I'm guessing the buildbots might do? I can fix that code if you point me to it, so I can merge this.

**Comment by kshyatt** [comment]
@IainNZ I can take a look at CoverageBase tonight, that's what will need to be changed. @timholy might want to take a look too. Ideally we can leave the buildbots mostly untouched...

**Comment by IainNZ** [comment]
OK, cool. Conceptually, biggest change is process_file returns a FileCoverage object, and process_folder returns a vector of these. I'm expecting most breakage to come from that.

**Comment by timholy** [comment]
Looks like a nice cleanup to me, thanks for doing this.

**Pull request merged**
