### PR TITLE
Fix codecov integration with travis

### PR DESCRIPTION
**Pull request by felipenoris**

### CODE REVIEW

**Comment by felipenoris** [comment]
Always a pleasure to learn new stuff.
Rebased instead of merged.

**Comment by kshyatt** [comment]
Nice! Thanks for doing this. I'll ping @IainNZ again, but this LGTM to merge and then we can tag.

**Comment by felipenoris** [comment]
Cool. Take your time.

**Comment by kshyatt** [comment]
BTW, just for reference, you could have force-pushed to the remote branch in your old PR, and not have had to close it and open this one.

**Comment by rsrock** [comment]
Aha, looks like I found my solution right here.  May I ask for a merge and tag, please?

**Comment by kshyatt** [comment]
I think it's been long enough that @IainNZ has had time to say his piece if he had one to say. I'll merge. I may not be able to tag, though! If you need this, use `Pkg.checkout("Coverage")` until the tag.

**Comment by rsrock** [comment]
Wow, that was quick.  Thanks!  I'll check it out.

**Comment by rsrock** [comment]
Works great.  Thanks again.

**Comment by kshyatt** [comment]
No problem. Thanks for reminding me to do this.

**Pull request merged**
