### PR TITLE
Wrote submit-token function for codecov

### PR DESCRIPTION
**Pull request by kshyatt**
This is currently working on https://codecov.io/github/kshyatt/julia?ref=master!

### CODE REVIEW

**Comment by IainNZ** [comment]
Dang thats cool. Feel free to tag a new release, might as well tag v0.1

**Comment by kshyatt** [comment]
Github is being extremely stupid and my 2FA isn't working. Can one tag using only the web interface?

**Comment by IainNZ** [comment]
Ehh, maybe, maybe not. I'll just do it and save us having to find out!

**Comment by kshyatt** [comment]
BTW I have confirmed that this works for packages, not just base. My own `CUSPARSE.jl` is now sporting a codecov badge.

**Comment by garborg** [comment]
This is awesome, you two! Excited to try it out with partial coverage stats provided by Base.

**Pull request merged**
